### ISSUE TITLE
Minor thing with the readme

### ISSUE THREAD

**Issue by Plaer1** [ProGamerGov/Neural-Zoom-Legacy#1]
The thing reads like this:
> Or if you are using Fast-Neural-Style, run:
>
> ./neural-zoom.sh input_file model_file zoom_value rotation_value num_frames 

Is it supposed to read like this?:

> Or if you are using Fast-Neural-Style, run:
>
> ./fast-neural-zoom.sh input_file model_file zoom_value rotation_value num_frames`

**Comment by ProGamerGov** [comment]
Thanks! I have resolved the issue.
