### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by StoneCypher** [ProGamerGov/Neural-Zoom-Legacy#4]
I would be interested to learn what texture you used on your film clips

They're purty

(also this tool is rly cool and thank you; not only is it useful, but it gets me thinking what other adaptations can change the core concept of style transfer with relatively little novel code)

**Comment by ProGamerGov** [comment]
The fast style transfer triangle zoom used the "triangle style" model from: https://github.com/ProGamerGov/Torch-Models

For the "cosmic style" I used this: https://i.imgur.com/fZhdk7z.jpg, which I think is a cropped version of: https://i.imgur.com/eVAECXx.jpg. If you need them to have a higher resolution, tools like Waifu2x work really well one them.

**Comment by StoneCypher** [comment]
thanks 😄

**Comment by ProGamerGov** [comment]
@StoneCypher If you are interested, I rebuilt Neural-Zoom in Python here: https://github.com/ProGamerGov/Neural-Zoom

The new Neural-Zoom should be a lot more user friendly and easy to use. It also has a bunch of new and useful features.

**Comment by StoneCypher** [comment]
actually i mostly am still having trouble correctly making one of these fast style transfer nets :(

**Comment by StoneCypher** [comment]
there's something in the dependencies that i can't figure out

i've uninstalled and reinstalled lua and torch so many times at this point

**Comment by ProGamerGov** [comment]
@StoneCypher What's the error? If it's related to `qlua`, then you can probably just use `th` instead. This fix worked for me with CNNMRF, and I can't see why it wouldn't work with Fast-Neural-Style.
